apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app: ${DEPLOYMENT_NAME}
    spec:
      containers:
      - name: ${DEPLOYMENT_NAME}
        image: ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: $CI_PROJECT_ROOT_NAMESPACE-secret
